### ISSUE TITLE
Duplicate Error with Slots

### ISSUE THREAD

**Issue by Silencedpulse** [allegro/ralph#3099] opened 2017-06-22 14:13 UTC
When duplicating a hardware object that has Slots assigned, this error is displayed:
'MultiForm' has no field named 'slot_no'.
Request Method:	POST
Request URL:	http://X.X.X.X:8000/data_center/datacenterasset/26/multiadd/
Django Version:	1.8.18
Exception Type:	ValueError
Exception Value:	
'MultiForm' has no field named 'slot_no'.
Exception Location:	/opt/ralph/ralph-core/lib/python3.4/site-packages/django/forms/forms.py in add_error, line 360

**Comment by MrEsL** [comment] 2017-06-28 13:02
Have the same problem.

**Comment by mkurek** [comment] 2017-10-12 11:27
Possibly duplicate of #3145

**Comment by romcheg** [comment] 2019-02-27 12:55
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group

**Closed as completed by romcheg** 2019-02-27 12:55 UTC
Labels: bug, hacktoberfest
