### ISSUE TITLE
Doubled values in "Content type" list @ /admin/cmdb/ci/-ci_id-

### ISSUE THREAD

**Issue by damian1976** [allegro/ralph#1181] opened 2014-11-04 09:35 UTC
![reseda_captcha](https://cloud.githubusercontent.com/assets/9283029/4897378/9aeb2b4a-6405-11e4-80f1-bde1e360287b.JPG)

**Comment by vi4m** [comment] 2015-04-24 07:01
Probably you imported fixtures twice - can't reproduce here.

**Comment by mkurek** [comment] 2015-04-24 07:08
Actually no - it's content type so it's independent with fixtures. We have 3 ip address models:

```
>>> ContentType.objects.filter(name__icontains='address').values_list('app_label', 'name')
[(u'discovery', u'IP address'), (u'activitylog', u'IP address'), (u'activitylog', u'IP address')]
```

one is in ralph discovery app and two are in lck.django activitylog

On the other hand @damian1976 why are you adding CI through admin panel? Can't you just use `<RALPH_URL>/cmdb/add/`?

**Comment by damian1976** [comment] 2015-04-24 08:56
@mkurek. I didn't add anything through admin panel. This is jus what I have - probably from the beginning of my ralph installation. If there are any distinctions between "identical" values they should be somehow differentiated.

**Comment by mkurek** [comment] 2015-04-24 09:00
@damian1976 yes - i know that you didn't add it. I've asked why do you add **CI** through admin panel, not CMDB gui?

**Comment by damian1976** [comment] 2015-04-24 09:01
@mkurek As far as I remember I didn't add anything (including CI) through admin module in this case

**Comment by vi4m** [comment] 2015-04-26 12:19
But the screen shows adding the ci

**Comment by damian1976** [comment] 2015-04-27 08:49
In my case you can see exactly same screen by random EDIT any of existing devices.

**Comment by vi4m** [comment] 2015-04-27 11:28
Not true. Just paste admin url you visited + full screenshot

**Comment by damian1976** [comment] 2015-04-27 11:41
Ok, if you say so:) This is the EDIT mode, not ADD:
/admin/cmdb/ci/682/
![screenshot](https://cloud.githubusercontent.com/assets/9283029/7346866/e803541e-ece2-11e4-97c7-6ef9853e3d69.JPG)

**Comment by vi4m** [comment] 2015-04-27 12:27
Ok here's the admin's view of CMDB Ci's. What was  the reason you get there ;-) Did you want to edit something ? You should not edit anything from there.

**Comment by damian1976** [comment] 2015-04-27 14:15
OK. Anyway the names are misleading :) It was the only reason to raise this issue.

**Comment by vi4m** [comment] 2015-04-27 18:42
I will close this issue, because it's not the problem with this form. Form correctly show all of the models types across multiple applications. And yes, we know about it.

**Comment by vi4m** [comment] 2015-04-27 18:42
We probably should disable CI's from admin interface, i would say.

**Closed by vi4m** 2015-04-27 18:42 UTC
