### ISSUE TITLE
Cannot import simple data

### ISSUE THREAD

**Issue by fossilet** [allegro/ralph#2187] opened 2016-01-29 07:05 UTC
I have an test asset CSV file for importing:

```
rack,budget_info,parent,model,management_ip,service_env,asset_ptr,baseobject_ptr,id,created,modified,content_type,remarks,hostname,sn,barcode,niw,required_support,order_no,invoice_no,invoice_date,price,provider,depreciation_rate,force_depreciation,depreciation_end_date,task_url,property_of,status,position,orientation,slot_no,connections,source,delivery_date,production_year,production_use_date,management_hostname,tags
,,,1,,1,,,,,,,,,6CU543YD7R,,,,,,,,,,,,,,,,,,,,,,,,
```

But I am seeing errors (I have enabled full traceback):

```
Line number: 1 - Cannot assign None: "DataCenterAsset.model" does not allow null values.
Traceback (most recent call last):
File "/home/vagrant/lib/python3.4/site-packages/import_export/resources.py", line 360, in import_data
self.import_obj(instance, row, real_dry_run)
File "/home/vagrant/lib/python3.4/site-packages/import_export/resources.py", line 226, in import_obj
self.import_field(field, obj, data)
File "/home/vagrant/lib/python3.4/site-packages/import_export/resources.py", line 218, in import_field
field.save(obj, data)
File "/home/vagrant/lib/python3.4/site-packages/import_export/fields.py", line 94, in save
setattr(obj, self.attribute, self.clean(data))
File "/home/vagrant/lib/python3.4/site-packages/django/db/models/fields/related.py", line 634, in __set__
(instance._meta.object_name, self.field.name)
ValueError: Cannot assign None: "DataCenterAsset.model" does not allow null values.
```

I am sure I have an asset model record with an `id` of  1.

I have found the crux of the problem is at `src/ralph/data_importer/widgets.py`,  in which the following statement yields nothing:

```
    imported_obj = ImportedObjects.objects.filter(
        content_type=content_type,
        old_object_pk=str(old_pk)
    ).first()
```

How can I fix this problem?

**Comment by szok** [comment] 2016-01-29 08:03
Have you imported from GUI or CLI ?

**Comment by fossilet** [comment] 2016-01-29 08:05
From GUI and the latest `ng` branch.

**Comment by vi4m** [comment] 2016-01-29 08:25
So it's the Ralph 2 compatibility layer. In the case of new data, i think that `get_imported_obj` should just simply return the same model as requested (without translation) so the function body should just `return (None, model)`

**Comment by vi4m** [comment] 2016-01-29 08:26
We could simple add settings or commandline flag to decide which import method to use. 

For gui import, we should not translate models, for commandline ralph 2.x import we should enable it from CLI when requested.

**Comment by mkurek** [comment] 2016-02-01 16:39
This will be fixed in #2192

**Comment by mkurek** [comment] 2016-02-16 08:15
Fixed in #2192

**Comment by fossilet** [comment] 2016-02-16 09:10
Import is still impossible:

```
Line number: 1 - list index out of range
Traceback (most recent call last):
File "/home/vagrant/lib/python3.4/site-packages/import_export/resources.py", line 360, in import_data
self.import_obj(instance, row, real_dry_run)
File "/home/vagrant/lib/python3.4/site-packages/import_export/resources.py", line 226, in import_obj
self.import_field(field, obj, data)
File "/home/vagrant/lib/python3.4/site-packages/import_export/resources.py", line 218, in import_field
field.save(obj, data)
File "/home/vagrant/lib/python3.4/site-packages/import_export/fields.py", line 94, in save
setattr(obj, self.attribute, self.clean(data))
File "/home/vagrant/lib/python3.4/site-packages/import_export/fields.py", line 57, in clean
value = self.widget.clean(value)
File "/home/vagrant/src/ralph/src/ralph/data_importer/widgets.py", line 188, in clean
environment__name=value[1]
IndexError: list index out of range
```

**Comment by fossilet** [comment] 2016-02-16 09:17
Import is still impossible:

```
Line number: 1 - list index out of range
Traceback (most recent call last):
File "/home/vagrant/lib/python3.4/site-packages/import_export/resources.py", line 360, in import_data
self.import_obj(instance, row, real_dry_run)
File "/home/vagrant/lib/python3.4/site-packages/import_export/resources.py", line 226, in import_obj
self.import_field(field, obj, data)
File "/home/vagrant/lib/python3.4/site-packages/import_export/resources.py", line 218, in import_field
field.save(obj, data)
File "/home/vagrant/lib/python3.4/site-packages/import_export/fields.py", line 94, in save
setattr(obj, self.attribute, self.clean(data))
File "/home/vagrant/lib/python3.4/site-packages/import_export/fields.py", line 57, in clean
value = self.widget.clean(value)
File "/home/vagrant/src/ralph/src/ralph/data_importer/widgets.py", line 188, in clean
environment__name=value[1]
IndexError: list index out of range
```

**Comment by mkurek** [comment] 2016-02-16 09:21
@szok please look at this error

**Comment by szok** [comment] 2016-02-16 09:34
@fossilet  Is the file that was imported was exported from Ralph after my bugfixes?
You can paste a several lines from this file?

**Comment by fossilet** [comment] 2016-02-16 09:36
@szok it was coined. The file content is the same as the one in the first comment.

**Comment by szok** [comment] 2016-02-16 09:40
This does not work, you have more time to download data from Ralph and only re-import them.

If you import data from another system it has to be imported by the command `ralph importer --help`

**Comment by fossilet** [comment] 2016-02-16 09:42
What's the requirement for the CSV file to be imported either via GUI or CLI?

**Comment by szok** [comment] 2016-02-16 09:56
If you import data from another system, then you have the CLI. Because there Id map the old to the new.

If you want to import from GUI is only in accordance with the format of which is exported.

After the recent changes he has changed and you need to CSV adapt to what is the latest Ralph.

**Comment by fossilet** [comment] 2016-02-16 10:16
@szok thanks. I am trying to adapt an Excel file (our legacy records, not from any system) to a CSV format that is acceptable to Ralph batch import mechanism. Let me see if I can succeed.

**Comment by fossilet** [comment] 2016-02-17 07:10
Although some fields are not required, i.e. orientation and depreciation_rate, why is the CLI import tool asking values for them? I suppose it would accept empty values.

**Comment by szok** [comment] 2016-02-17 07:21
CLI command was designed mainly to import data from old Ralph and keeping up with information about the old ID records.

**Comment by fossilet** [comment] 2016-02-17 08:14
Thanks @szok. What do you recommend to be the preferred tool for me, to import from an manually edited Excel sheet that is not from any system? From what I have learned now, should I fill the exported CSV format from the GUI with my data, and possibly with the right ID and str for required fields, i.e. service_env and service_env_str?

**Closed as completed** 2016-02-18 09:46 UTC
Labels: bug, ng

**Comment by szok** [comment] 2016-02-18 09:52
Yes as you write.
After the export of the GUI, modify their values in columns but try to be compatible with the format of export, then it will work.
When importing columns \* _str are ignored, import only ID's or service_env = "foo | bar", etc

**Comment by fossilet** [comment] 2016-02-18 10:32
Thanks @szok .
